version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
    groups:
      react-router:
        patterns:
          - 'react-router-dom'
          - '@remix-run/router'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
