root: true
extends: ['@faergeek']
plugins: [simple-import-sort]
rules:
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
overrides:
  - files: '*'
    env: { node: true }
  - files: src/**/*
    extends: ['@faergeek/eslint-config/react']
