app = "js-webapp-template"

[experimental]
auto_rollback = true

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "requests"
hard_limit = 25
soft_limit = 20

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
restart_limit = 0
method = "get"
path = "/"
protocol = "http"
