name: Main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          restore-keys: |
            ${{ runner.os }}-yarn-
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: |
            ~/.cache/yarn
            node_modules
      - name: Install dependencies
        run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - name: Check code formatting
        run: yarn run prettier:check
      - name: Lint
        run: yarn run lint
      - name: Check types
        run: yarn run typecheck
